services:
  app:
    image: ghcr.io/a1exymoroz/nastolka-api:latest
    container_name: nastolka-api
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"

  caddy:
    image: caddy:2-alpine
    container_name: nastolka-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
