-- Reset games table to match current entity (id, name, description, photo, bgg_id)
-- Run when you see errors like: null value in column "available" violates not-null constraint

DROP TABLE IF EXISTS games;

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    photo VARCHAR(2048) NOT NULL,
    bgg_id BIGINT UNIQUE
);
