-- Reset games, game_expansions, locations, location_games, location_game_expansions,
-- location_shares, location_history and location_history_players tables to match
-- current entities.
-- Run when you see errors like: null value in column "available" violates not-null constraint

DROP TABLE IF EXISTS location_history_players;
DROP TABLE IF EXISTS location_history;
DROP TABLE IF EXISTS location_game_expansions;
DROP TABLE IF EXISTS location_games;
DROP TABLE IF EXISTS location_shares;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS game_expansions;
DROP TABLE IF EXISTS games;

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    photo VARCHAR(2048) NOT NULL,
    bgg_id BIGINT UNIQUE,
    min_players INTEGER,
    max_players INTEGER,
    min_play_time INTEGER,
    max_play_time INTEGER
);

CREATE TABLE game_expansions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    photo VARCHAR(2048) NOT NULL,
    bgg_id BIGINT UNIQUE
);

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000)
);

CREATE TABLE location_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (location_id, user_id)
);

CREATE TABLE location_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    UNIQUE (location_id, game_id)
);

CREATE TABLE location_game_expansions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_game_id BIGINT NOT NULL REFERENCES location_games(id) ON DELETE CASCADE,
    expansion_id BIGINT NOT NULL REFERENCES game_expansions(id) ON DELETE CASCADE,
    UNIQUE (location_game_id, expansion_id)
);

CREATE TABLE location_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    played_at TIMESTAMP NOT NULL,
    state VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    rating INTEGER,
    photo VARCHAR(255)
);

CREATE TABLE location_history_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id BIGINT NOT NULL REFERENCES location_history(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    placement INTEGER,
    points INTEGER,
    UNIQUE (history_id, user_id),
    UNIQUE (history_id, placement)
);
