CREATE TABLE pick_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    created_by_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL DEFAULT 'WAITING_FOR_PLAYERS',
    exclude_already_played BOOLEAN NOT NULL DEFAULT FALSE,
    target_remaining_count INTEGER NOT NULL,
    required_ban_count INTEGER,
    ban_count INTEGER NOT NULL DEFAULT 0,
    current_turn_index INTEGER,
    selected_game_id BIGINT REFERENCES games(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0
);

-- Enforces "only one active session per location" at the database level, not just in service code.
CREATE UNIQUE INDEX uq_pick_sessions_active_location
    ON pick_sessions(location_id)
    WHERE status IN ('WAITING_FOR_PLAYERS', 'IN_PROGRESS');

CREATE TABLE pick_session_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES pick_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    turn_order INTEGER,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (session_id, user_id)
);

CREATE TABLE pick_session_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES pick_sessions(id) ON DELETE CASCADE,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    action VARCHAR(16) NOT NULL DEFAULT 'UNDECIDED',
    acted_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    acted_at TIMESTAMPTZ,
    action_sequence INTEGER,
    UNIQUE (session_id, game_id)
);

CREATE INDEX idx_pick_session_participants_session ON pick_session_participants(session_id);
CREATE INDEX idx_pick_session_candidates_session ON pick_session_candidates(session_id);
