-- Baseline: represents the schema as it exists today, previously managed by
-- spring.jpa.hibernate.ddl-auto=update. From here on, schema changes go through
-- Flyway migrations instead of relying on Hibernate to alter tables in place.
-- On environments that already have this schema, spring.flyway.baseline-on-migrate
-- marks this version as applied without running it. On a brand-new database, this
-- script builds the schema from scratch.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(255) NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    photo VARCHAR(2048) NOT NULL,
    bgg_id BIGINT UNIQUE,
    min_players INTEGER,
    max_players INTEGER,
    min_play_time INTEGER,
    max_play_time INTEGER
);

CREATE TABLE game_expansions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    photo VARCHAR(2048) NOT NULL,
    bgg_id BIGINT UNIQUE
);

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000)
);

CREATE TABLE location_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (location_id, user_id)
);

CREATE TABLE location_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    UNIQUE (location_id, game_id)
);

CREATE TABLE location_game_expansions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_game_id BIGINT NOT NULL REFERENCES location_games(id) ON DELETE CASCADE,
    expansion_id BIGINT NOT NULL REFERENCES game_expansions(id) ON DELETE CASCADE,
    UNIQUE (location_game_id, expansion_id)
);

CREATE TABLE location_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    played_at TIMESTAMP NOT NULL,
    state VARCHAR(255) NOT NULL DEFAULT 'CREATED',
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    rating INTEGER,
    photo VARCHAR(255)
);

CREATE TABLE location_history_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id BIGINT NOT NULL REFERENCES location_history(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    placement INTEGER,
    points INTEGER,
    UNIQUE (history_id, user_id),
    UNIQUE (history_id, placement)
);

CREATE TABLE location_history_expansions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id BIGINT NOT NULL REFERENCES location_history(id) ON DELETE CASCADE,
    expansion_id BIGINT NOT NULL REFERENCES game_expansions(id) ON DELETE CASCADE,
    UNIQUE (history_id, expansion_id)
);
